# Use DecapBridge classic auth (required)
backend:
  name: git-gateway
  repo: zabriskies/kanae
  branch: main
  identity_url: https://auth.decapbridge.com/sites/f1884b66-b54d-4e43-9d0f-2cc36f38a11a
  gateway_url: https://gateway.decapbridge.com

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Journal（ブログ）"
    folder: "src/content/blog"
    create: true
    delete: true
    slug: "{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "概要", name: "description", widget: "text", required: false }
      - { label: "公開日", name: "pubDate", widget: "datetime" }
      - { label: "更新日", name: "updatedDate", widget: "datetime", required: false }
      - { label: "アイキャッチ画像", name: "heroImage", widget: "image", required: false }
      - { label: "下書きにする", name: "draft", widget: "boolean", default: false }
      - { label: "本文", name: "body", widget: "markdown" }pp